### ISSUE TITLE
A few questions about running insight-api on my local development

### ISSUE THREAD

**Issue by dcb9** [qtumproject/insight-api#8]
Hi,

## API error

After configuring qtumcore-node, qtumd and insight-api, I managed to access insight-api via the command below

```
$ curl localhost:3001/insight-api/supply
99982796%
```
But I got the error message `Method not found. Code:-32601%` when i tried to access `/insight-api/blocks`, `/insight-api/addr/qNupAvK5wXACXDgZNofaFpWDNePKtH5ZRm`, ...

## qtumcore-node error logs

```
insightapi_1  | [2018-08-13T15:13:34.391Z] error: [AddressBalanceService] Update Error { RPCError: Method not found
insightapi_1  |     at Qtum._wrapRPCError (/mynode/node_modules/qtumcore-node/lib/services/qtumd.js:552:13)
insightapi_1  |     at /mynode/node_modules/qtumcore-node/lib/services/qtumd.js:1214:30
insightapi_1  |     at IncomingMessage.<anonymous> (/mynode/node_modules/qtumd-rpc/lib/index.js:107:7)
insightapi_1  |     at emitNone (events.js:111:20)
insightapi_1  |     at IncomingMessage.emit (events.js:208:7)
insightapi_1  |     at endReadableNT (_stream_readable.js:1056:12)
insightapi_1  |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
insightapi_1  |     at process._tickCallback (internal/process/next_tick.js:180:9) code: -32601 }
```
Could anybody help me to figure it out?

Thanks

**Comment by hayeah** [comment]
problem solved. need t use qtum-core

**Comment by dcb9** [comment]
[insight API Dockerfile](https://github.com/dcb9/qtum-docker/tree/8251c9cb104a1dba86fb701e9b140c3c160c85b1/insightapi)
[insight API image](https://hub.docker.com/r/dcb9/qtum-insightapi/)
